In [3]:
import numpy as np
import pandas as pd

In [4]:
array1 = np.array([2,3,5,1,2,7])
print(array1)
array2 = np.zeros((2,8))
print(array2)
array3 = np.arange(25)
print(array3)
array4 = np.arange(25, 26, 0.1)
print(array4)

[2 3 5 1 2 7]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[25.  25.1 25.2 25.3 25.4 25.5 25.6 25.7 25.8 25.9]


In [5]:
array1[1]

3

In [10]:
array2[1,2:5]
array2[1,]
array2[1,2]

array([0., 0., 0.])

In [13]:
series = pd.Series(np.arange(10, 15, 0.1))
series

0     10.0
1     10.1
2     10.2
3     10.3
4     10.4
5     10.5
6     10.6
7     10.7
8     10.8
9     10.9
10    11.0
11    11.1
12    11.2
13    11.3
14    11.4
15    11.5
16    11.6
17    11.7
18    11.8
19    11.9
20    12.0
21    12.1
22    12.2
23    12.3
24    12.4
25    12.5
26    12.6
27    12.7
28    12.8
29    12.9
30    13.0
31    13.1
32    13.2
33    13.3
34    13.4
35    13.5
36    13.6
37    13.7
38    13.8
39    13.9
40    14.0
41    14.1
42    14.2
43    14.3
44    14.4
45    14.5
46    14.6
47    14.7
48    14.8
49    14.9
dtype: float64

In [16]:
dataframe = pd.DataFrame({'Name':pd.Series(np.arange(0, 10, 0.1)), 'Time':pd.Series(np.arange(15))})
dataframe.head()

Name  Time
0   0.0   0.0
1   0.1   1.0
2   0.2   2.0
3   0.3   3.0
4   0.4   4.0

In [17]:
array_df = dataframe.to_numpy()
array_df

array([[ 0. ,  0. ],
       [ 0.1,  1. ],
       [ 0.2,  2. ],
       [ 0.3,  3. ],
       [ 0.4,  4. ],
       [ 0.5,  5. ],
       [ 0.6,  6. ],
       [ 0.7,  7. ],
       [ 0.8,  8. ],
       [ 0.9,  9. ],
       [ 1. , 10. ],
       [ 1.1, 11. ],
       [ 1.2, 12. ],
       [ 1.3, 13. ],
       [ 1.4, 14. ],
       [ 1.5,  nan],
       [ 1.6,  nan],
       [ 1.7,  nan],
       [ 1.8,  nan],
       [ 1.9,  nan],
       [ 2. ,  nan],
       [ 2.1,  nan],
       [ 2.2,  nan],
       [ 2.3,  nan],
       [ 2.4,  nan],
       [ 2.5,  nan],
       [ 2.6,  nan],
       [ 2.7,  nan],
       [ 2.8,  nan],
       [ 2.9,  nan],
       [ 3. ,  nan],
       [ 3.1,  nan],
       [ 3.2,  nan],
       [ 3.3,  nan],
       [ 3.4,  nan],
       [ 3.5,  nan],
       [ 3.6,  nan],
       [ 3.7,  nan],
       [ 3.8,  nan],
       [ 3.9,  nan],
       [ 4. ,  nan],
       [ 4.1,  nan],
       [ 4.2,  nan],
       [ 4.3,  nan],
       [ 4.4,  nan],
       [ 4.5,  nan],
       [ 4.6,  nan],
       [ 4.7,

In [28]:
print(dataframe.iloc[1])

Name    0.1
Time    1.0
Name: 1, dtype: float64


In [29]:
dataframe.describe()

Name       Time
count  100.000000  15.000000
mean     4.950000   7.000000
std      2.901149   4.472136
min      0.000000   0.000000
25%      2.475000   3.500000
50%      4.950000   7.000000
75%      7.425000  10.500000
max      9.900000  14.000000